### ISSUE TITLE
如何判断爬虫的任务状态

### ISSUE THREAD

**Issue by q1179336367** [ScrapeOps/scrapeops-scrapy-sdk#6]
根据什么条件，可以判断爬虫的运行状态是running、waiting、fail

**Comment by josephkearney91** [comment]
According to what conditions, the running status of the crawler can be judged as running, waiting, or fail:

When the spider stops running due to an error in your spider, the logs do not get received by our API(due to a connection issue) after 3 re-tries it switches the status to **unknown** - this can also happen if the error logs are too big to transmit to our API and it stops transmitting to our backend.
